### PR TITLE
sequence diagram artifact

### PR DESCRIPTION
**Pull request by h1alexbel**
@l3r8yJ take a look please

---

## PR-Codex overview
This PR adds a PlantUML sequence diagram to illustrate the flow of data between various components of the system.

### Detailed summary
- Added a sequence diagram in `diagrams/sequence.puml`
- Includes actors `TelegramUser` and `Bot`
- Includes participants `Hub`, `Database`, `Notifications`, and `GitHub`
- Shows the flow of data between components through various tokens and data streams.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by l3r8yJ** [comment]
@h1alexbel how can I see the result, do I need to build it somehow or what?

**Comment by h1alexbel** [comment]
@l3r8yJ workflow should compile all the stuff

**Comment by h1alexbel** [comment]
@l3r8yJ I think it needs to be in master branch by default before compiling

see https://github.com/h1alexbel/test

**Review by l3r8yJ — APPROVED** [review]

**Comment by l3r8yJ** [comment]
@rultor merge

**Pull request merged**
